### ISSUE TITLE
Feature Request : Config option to disable FoV

### ISSUE THREAD

**Issue by JoelZBub** [Thretcha/RoadRunner#2]
A config option to toggle Field of View changes would be great.
This would be so that pack creators could make block speed increases match those added by mods such as chisel that don't add the potion style FoV change.

**Comment by Thretcha** [comment]
I checked the chisel code and they use a completely different way to handle the block speed increases. While I could completely rewrite my code to work the same way it would be a hack that is not meant to be used. I have come across this way of implementation before and was strongly advised against using it. 
The reason my mod causes those field of view changes is because it's correctly tied into the default minecraft code and the chisel mod is bypassing this by directly changing the players movement speed.
